import 'package:flutter/material.dart';

class ReportViewScreen extends StatelessWidget {
  const ReportViewScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final String type =
    ModalRoute.of(context)!.settings.arguments as String;

    return Scaffold(
      appBar: AppBar(
        title: const Text("Report"),
        backgroundColor: Colors.blueAccent,
        foregroundColor: Colors.white,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: type == "enrolment"
            ? _enrolmentReport()
            : _counsellingReport(),
      ),
    );
  }

  // ================= ENROLMENT REPORT =================
  Widget _enrolmentReport() {
    return _reportContainer(
      title: "STUDENT ENROLMENT REPORT",
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _headerInfo(),

          const SizedBox(height: 16),

          _table([
            ["No", "Name", "Faculty", "Level", "Programme", "Intake", "Status"],
            ["1", "Ali", "Computing", "Degree", "Software Eng", "May", "Approved"],
            ["2", "Tan", "Computing", "Degree", "Data Science", "Oct", "Pending"],
            ["3", "Kumar", "Engineering", "Diploma", "Mechanical", "May", "Approved"],
            ["4", "Siti", "Business", "Degree", "Accounting", "May", "Rejected"],
          ]),

          const SizedBox(height: 20),

          _summary({
            "Total Applications": "4",
            "Approved": "2",
            "Pending": "1",
            "Rejected": "1",
          }),
        ],
      ),
    );
  }

  // ================= COUNSELLING REPORT =================
  Widget _counsellingReport() {
    return _reportContainer(
      title: "COUNSELLING APPOINTMENT REPORT",
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _headerInfo(),

          const SizedBox(height: 16),

          _table([
            ["No", "Name", "Reason", "Date", "Time", "Type", "Status"],
            ["1", "Ali", "Academic", "10 Mar", "10:00 AM", "Online", "Completed"],
            ["2", "Tan", "Anxiety", "10 Mar", "2:00 PM", "Face-to-face", "Pending"],
            ["3", "Raj", "Financial", "11 Mar", "11:00 AM", "Online", "Completed"],
            ["4", "Siti", "Relationship", "11 Mar", "3:00 PM", "Online", "Cancelled"],
          ]),

          const SizedBox(height: 20),

          _summary({
            "Total Appointments": "4",
            "Completed": "2",
            "Pending": "1",
            "Cancelled": "1",
          }),
        ],
      ),
    );
  }

  // ================= COMMON UI =================

  Widget _reportContainer({required String title, required Widget child}) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: Colors.grey.shade400),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Center(
            child: Text(
              title,
              style: const TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
                letterSpacing: 1,
              ),
            ),
          ),
          const SizedBox(height: 12),
          const Divider(thickness: 1),
          child,
        ],
      ),
    );
  }

  Widget _headerInfo() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const [
        Text("SYSTEM NAME : E-Enrolment and E-Counselling System"),
        Text("GENERATED BY : Admin"),
        SizedBox(height: 6),
        Align(
          alignment: Alignment.centerRight,
          child: Text("DATE : 12 March 2026"),
        ),
      ],
    );
  }

  Widget _table(List<List<String>> rows) {
    return Table(
      border: TableBorder.all(color: Colors.grey.shade400),
      columnWidths: const {},
      children: rows.map((row) {
        final isHeader = rows.indexOf(row) == 0;

        return TableRow(
          decoration: BoxDecoration(
            color: isHeader ? Colors.grey.shade300 : Colors.transparent,
          ),
          children: row.map((cell) {
            return Padding(
              padding: const EdgeInsets.all(8),
              child: Text(
                cell,
                style: TextStyle(
                  fontWeight:
                  isHeader ? FontWeight.bold : FontWeight.normal,
                ),
              ),
            );
          }).toList(),
        );
      }).toList(),
    );
  }

  Widget _summary(Map<String, String> data) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: data.entries.map((e) {
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 2),
          child: Text("${e.key} : ${e.value}"),
        );
      }).toList(),
    );
  }
}