// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALonDtjzpezScxSEDImEEzcbXzj_9XfPw',
    appId: '1:993549250235:web:c147545b118acf6321039e',
    messagingSenderId: '993549250235',
    projectId: 'e-enrolment-n-e-counselling',
    authDomain: 'e-enrolment-n-e-counselling.firebaseapp.com',
    storageBucket: 'e-enrolment-n-e-counselling.firebasestorage.app',
    measurementId: 'G-BMPHSY89V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQZmUPn7TVND9HzX99wCk_XfuxE2y974',
    appId: '1:993549250235:android:98aa110a6902c0f921039e',
    messagingSenderId: '993549250235',
    projectId: 'e-enrolment-n-e-counselling',
    storageBucket: 'e-enrolment-n-e-counselling.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMr2mLggXJkaTmtuQIVT1v6w9nAaOJeVk',
    appId: '1:993549250235:ios:23f56c50c98fca6321039e',
    messagingSenderId: '993549250235',
    projectId: 'e-enrolment-n-e-counselling',
    storageBucket: 'e-enrolment-n-e-counselling.firebasestorage.app',
    iosBundleId: 'FYP.com.eEnrolmentAndECounsellingAppication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMr2mLggXJkaTmtuQIVT1v6w9nAaOJeVk',
    appId: '1:993549250235:ios:23f56c50c98fca6321039e',
    messagingSenderId: '993549250235',
    projectId: 'e-enrolment-n-e-counselling',
    storageBucket: 'e-enrolment-n-e-counselling.firebasestorage.app',
    iosBundleId: 'FYP.com.eEnrolmentAndECounsellingAppication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALonDtjzpezScxSEDImEEzcbXzj_9XfPw',
    appId: '1:993549250235:web:3b6a238679fa28ed21039e',
    messagingSenderId: '993549250235',
    projectId: 'e-enrolment-n-e-counselling',
    authDomain: 'e-enrolment-n-e-counselling.firebaseapp.com',
    storageBucket: 'e-enrolment-n-e-counselling.firebasestorage.app',
    measurementId: 'G-XNHSGE26ZH',
  );
}
