import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../config/app_config.dart';
import '../services/report_service.dart';

/// Builds PDF documents for admin enrolment and counselling reports.
class ReportPdfGenerator {
  ReportPdfGenerator._();

  static pw.Document buildEnrolmentDocument({
    required EnrolmentReportData data,
    required DateTime generatedAt,
    DateTime? fromDate,
    DateTime? toDate,
  }) {
    final tableHeaders = [
      'No',
      'Student Name',
      'Course Name',
      'Status',
      'Application Date',
    ];

    final tableRows = data.rows.asMap().entries.map((entry) {
      final row = entry.value;
      return [
        '${entry.key + 1}',
        row.studentName,
        row.courseName,
        row.status.firestoreValue,
        ReportFormatting.formatShortDate(row.appliedAt),
      ];
    }).toList();

    return _buildDocument(
      reportTitle: 'STUDENT ENROLMENT REPORT',
      generatedAt: generatedAt,
      fromDate: fromDate,
      toDate: toDate,
      summary: data.summary.asLabelMap,
      tableHeaders: tableHeaders,
      tableRows: tableRows,
    );
  }

  static pw.Document buildCounsellingDocument({
    required CounsellingReportData data,
    required DateTime generatedAt,
    DateTime? fromDate,
    DateTime? toDate,
  }) {
    final tableHeaders = [
      'No',
      'Student Name',
      'Counsellor Name',
      'Appointment Date',
      'Mode',
      'Status',
    ];

    final tableRows = data.rows.asMap().entries.map((entry) {
      final row = entry.value;
      return [
        '${entry.key + 1}',
        row.studentName,
        row.counsellorName,
        ReportFormatting.formatShortDate(row.appointmentDate),
        row.mode,
        row.status.firestoreValue,
      ];
    }).toList();

    return _buildDocument(
      reportTitle: 'COUNSELLING APPOINTMENT REPORT',
      generatedAt: generatedAt,
      fromDate: fromDate,
      toDate: toDate,
      summary: data.summary.asLabelMap,
      tableHeaders: tableHeaders,
      tableRows: tableRows,
      landscape: true,
    );
  }

  static pw.Document _buildDocument({
    required String reportTitle,
    required DateTime generatedAt,
    required DateTime? fromDate,
    required DateTime? toDate,
    required Map<String, String> summary,
    required List<String> tableHeaders,
    required List<List<String>> tableRows,
    bool landscape = false,
  }) {
    final doc = pw.Document();
    final generatedLabel = ReportFormatting.formatLongDate(generatedAt);
    final periodLabel = ReportFormatting.formatPeriod(fromDate, toDate);

    doc.addPage(
      pw.MultiPage(
        pageFormat: landscape ? PdfPageFormat.a4.landscape : PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) {
          return [
            pw.Text(
              AppConfig.universityName,
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              'E-Enrolment and E-Counselling System',
              style: const pw.TextStyle(fontSize: 11),
            ),
            pw.SizedBox(height: 20),
            pw.Center(
              child: pw.Text(
                reportTitle,
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                  letterSpacing: 1,
                ),
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Text('Generated Date : $generatedLabel'),
            pw.Text('Selected Period : $periodLabel'),
            pw.Text('Generated By : Admin'),
            pw.SizedBox(height: 16),
            pw.Text(
              'Summary',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 6),
            ...summary.entries.map(
              (entry) => pw.Text('${entry.key} : ${entry.value}'),
            ),
            pw.SizedBox(height: 16),
            pw.Text(
              'Report Data',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 8),
            if (tableRows.isEmpty)
              pw.Text(
                'No records found for the selected period.',
                style: const pw.TextStyle(fontSize: 10),
              )
            else
              _buildPdfTable(tableHeaders, tableRows),
          ];
        },
      ),
    );

    return doc;
  }

  static pw.Widget _buildPdfTable(
    List<String> headers,
    List<List<String>> rows,
  ) {
    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: rows,
      headerStyle: pw.TextStyle(
        fontWeight: pw.FontWeight.bold,
        fontSize: 9,
      ),
      cellStyle: const pw.TextStyle(fontSize: 8),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
      border: pw.TableBorder.all(color: PdfColors.grey600, width: 0.5),
      cellAlignment: pw.Alignment.centerLeft,
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 4),
    );
  }

  static String fileName({
    required String type,
    DateTime? fromDate,
    DateTime? toDate,
  }) {
    final suffix = ReportFormatting.pdfFileSuffix(fromDate, toDate);
    return '$type-report-$suffix.pdf';
  }
}
